export const MY_CHATS_SUCCESS = "MY_CHATS_SUCCESS";
export const MY_CHATS_FAIL = "MY_CHATS_FAIL";

export const GET_CHATS_SUCCESS = "GET_CHATS_SUCCESS";
export const GET_CHATS_FAIL = "GET_CHATS_FAIL";

export const GET_CHAT_DETAIL_SUCCESS = "GET_CHAT_DETAIL_SUCCESS";
export const GET_CHAT_DETAIL_FAIL = "GET_CHAT_DETAIL_FAIL";

export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";
